trigger:
  - dev

pool:
  vmImage: windows-latest

variables:
  advancedsecurity.codeql.querysuite: security-extended
  advancedsecurity.submittoadvancedsecurity: true

steps:

  - task: AdvancedSecurity-Codeql-Init@1
    inputs:
      languages: "csharp"
      # Supported languages: csharp, cpp, go, java, javascript, python, ruby, swift
      # You can customize the initialize task: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/advanced-security-codeql-init-v1?view=azure-pipelines
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
  - task: VSBuild@1
    inputs:
      solution: '**\*.sln'
      maximumCpuCount: true
      msbuildArchitecture: 'x64'
# It's possible that the the autobuild step does not execute, specifically if you are scanning a language like cpp, java, csharp, or swift.
# If the above does not execute correctly, you can replace the Autobuild task with your customized build. E.g.:

  - task: AdvancedSecurity-Dependency-Scanning@1 # More details on this task: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/advanced-security-dependency-scanning-v1?view=azure-pipelines

  - task: AdvancedSecurity-Codeql-Analyze@1 # More details on this task: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/advanced-security-codeql-analyze-v1?view=azure-pipelines