// <auto-generated />
namespace sReportsV2.Domain.Sql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddAttendingDoctors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAttendingDoctors));
        
        string IMigrationMetadata.Id
        {
            get { return "202305220701429_AddAttendingDoctors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
