namespace sReportsV2.Domain.Sql.Migrations
{
    using sReportsV2.DAL.Sql.Sql;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddEntityStateToEntity : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Addresses", "EntityStateCD", c => c.Int());
            AddColumn("dbo.Codes", "EntityStateCD", c => c.Int());
            AddColumn("dbo.Personnel", "EntityStateCD", c => c.Int());
            AddColumn("dbo.Organizations", "EntityStateCD", c => c.Int());
            AddColumn("dbo.OrganizationClinicalDomains", "EntityStateCD", c => c.Int());
            AddColumn("dbo.OrganizationIdentifiers", "EntityStateCD", c => c.Int());
            AddColumn("dbo.OrganizationRelations", "EntityStateCD", c => c.Int());
            AddColumn("dbo.PersonnelTeamOrganizationRelations", "EntityStateCD", c => c.Int());
            AddColumn("dbo.PersonnelTeams", "EntityStateCD", c => c.Int());
            AddColumn("dbo.PersonnelTeamRelations", "EntityStateCD", c => c.Int());
            AddColumn("dbo.Telecoms", "EntityStateCD", c => c.Int());
            AddColumn("dbo.PersonnelAcademicPositions", "EntityStateCD", c => c.Int());
            AddColumn("dbo.PersonnelAddresses", "EntityStateCD", c => c.Int());
            AddColumn("dbo.PersonnelIdentifiers", "EntityStateCD", c => c.Int());
            AddColumn("dbo.PersonnelPositions", "EntityStateCD", c => c.Int());
            AddColumn("dbo.ThesaurusEntries", "EntityStateCD", c => c.Int());
            AddColumn("dbo.ChemotherapySchemaInstances", "EntityStateCD", c => c.Int());
            AddColumn("dbo.ChemotherapySchemas", "EntityStateCD", c => c.Int());
            AddColumn("dbo.Medications", "EntityStateCD", c => c.Int());
            AddColumn("dbo.ChemotherapySchemaInstanceVersions", "EntityStateCD", c => c.Int());
            AddColumn("dbo.MedicationReplacements", "EntityStateCD", c => c.Int());
            AddColumn("dbo.MedicationInstances", "EntityStateCD", c => c.Int());
            AddColumn("dbo.SmartOncologyPatients", "EntityStateCD", c => c.Int());
            AddColumn("dbo.EpisodeOfCares", "EntityStateCD", c => c.Int());
            AddColumn("dbo.CodeAssociations", "EntityStateCD", c => c.Int());
            AddColumn("dbo.CodeSets", "EntityStateCD", c => c.Int());
            AddColumn("dbo.Comments", "EntityStateCD", c => c.Int());
            AddColumn("dbo.PatientContacts", "EntityStateCD", c => c.Int());
            AddColumn("dbo.Patients", "EntityStateCD", c => c.Int());
            AddColumn("dbo.PatientAddresses", "EntityStateCD", c => c.Int());
            AddColumn("dbo.PatientIdentifiers", "EntityStateCD", c => c.Int());
            AddColumn("dbo.PatientTelecoms", "EntityStateCD", c => c.Int());
            AddColumn("dbo.PatientContactAddresses", "EntityStateCD", c => c.Int());
            AddColumn("dbo.PatientContactTelecoms", "EntityStateCD", c => c.Int());
            AddColumn("dbo.Encounters", "EntityStateCD", c => c.Int());
            AddColumn("dbo.GlobalThesaurusRoles", "EntityStateCD", c => c.Int());
            AddColumn("dbo.GlobalThesaurusUserRoles", "EntityStateCD", c => c.Int());
            AddColumn("dbo.GlobalThesaurusUsers", "EntityStateCD", c => c.Int());
            AddColumn("dbo.InboundAliases", "EntityStateCD", c => c.Int());
            AddColumn("dbo.OutboundAliases", "EntityStateCD", c => c.Int());
            AddColumn("dbo.OutsideUsers", "EntityStateCD", c => c.Int());
            AddColumn("dbo.PositionPermissions", "EntityStateCD", c => c.Int());
            AddColumn("dbo.ThesaurusMerges", "EntityStateCD", c => c.Int());
            AddColumn("dbo.EncounterIdentifiers", "EntityStateCD", c => c.Int());
            AddColumn("dbo.ErrorMessageLogs", "EntityStateCD", c => c.Int());
            AddColumn("dbo.HL7MessageLog", "EntityStateCD", c => c.Int());
            AddColumn("dbo.ProcedeedMessageLogs", "EntityStateCD", c => c.Int());
            CreateIndex("dbo.Addresses", "EntityStateCD");
            CreateIndex("dbo.Codes", "EntityStateCD");
            CreateIndex("dbo.Personnel", "EntityStateCD");
            CreateIndex("dbo.Organizations", "EntityStateCD");
            CreateIndex("dbo.OrganizationClinicalDomains", "EntityStateCD");
            CreateIndex("dbo.OrganizationIdentifiers", "EntityStateCD");
            CreateIndex("dbo.OrganizationRelations", "EntityStateCD");
            CreateIndex("dbo.PersonnelTeamOrganizationRelations", "EntityStateCD");
            CreateIndex("dbo.PersonnelTeams", "EntityStateCD");
            CreateIndex("dbo.PersonnelTeamRelations", "EntityStateCD");
            CreateIndex("dbo.Telecoms", "EntityStateCD");
            CreateIndex("dbo.PersonnelAcademicPositions", "EntityStateCD");
            CreateIndex("dbo.PersonnelAddresses", "EntityStateCD");
            CreateIndex("dbo.PersonnelIdentifiers", "EntityStateCD");
            CreateIndex("dbo.PersonnelPositions", "EntityStateCD");
            CreateIndex("dbo.ThesaurusEntries", "EntityStateCD");
            CreateIndex("dbo.ChemotherapySchemaInstances", "EntityStateCD");
            CreateIndex("dbo.ChemotherapySchemas", "EntityStateCD");
            CreateIndex("dbo.Medications", "EntityStateCD");
            CreateIndex("dbo.ChemotherapySchemaInstanceVersions", "EntityStateCD");
            CreateIndex("dbo.MedicationReplacements", "EntityStateCD");
            CreateIndex("dbo.MedicationInstances", "EntityStateCD");
            CreateIndex("dbo.SmartOncologyPatients", "EntityStateCD");
            CreateIndex("dbo.EpisodeOfCares", "EntityStateCD");
            CreateIndex("dbo.CodeAssociations", "EntityStateCD");
            CreateIndex("dbo.CodeSets", "EntityStateCD");
            CreateIndex("dbo.Comments", "EntityStateCD");
            CreateIndex("dbo.PatientContacts", "EntityStateCD");
            CreateIndex("dbo.Patients", "EntityStateCD");
            CreateIndex("dbo.PatientAddresses", "EntityStateCD");
            CreateIndex("dbo.PatientIdentifiers", "EntityStateCD");
            CreateIndex("dbo.PatientTelecoms", "EntityStateCD");
            CreateIndex("dbo.PatientContactAddresses", "EntityStateCD");
            CreateIndex("dbo.PatientContactTelecoms", "EntityStateCD");
            CreateIndex("dbo.Encounters", "EntityStateCD");
            CreateIndex("dbo.GlobalThesaurusRoles", "EntityStateCD");
            CreateIndex("dbo.GlobalThesaurusUserRoles", "EntityStateCD");
            CreateIndex("dbo.GlobalThesaurusUsers", "EntityStateCD");
            CreateIndex("dbo.InboundAliases", "EntityStateCD");
            CreateIndex("dbo.OutboundAliases", "EntityStateCD");
            CreateIndex("dbo.OutsideUsers", "EntityStateCD");
            CreateIndex("dbo.PositionPermissions", "EntityStateCD");
            CreateIndex("dbo.ThesaurusMerges", "EntityStateCD");
            CreateIndex("dbo.EncounterIdentifiers", "EntityStateCD");
            CreateIndex("dbo.ErrorMessageLogs", "EntityStateCD");
            CreateIndex("dbo.HL7MessageLog", "EntityStateCD");
            CreateIndex("dbo.ProcedeedMessageLogs", "EntityStateCD");
            AddForeignKey("dbo.Personnel", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.OrganizationClinicalDomains", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.Organizations", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.OrganizationIdentifiers", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.OrganizationRelations", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.PersonnelTeamOrganizationRelations", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.PersonnelTeams", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.PersonnelTeamRelations", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.Telecoms", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.PersonnelAcademicPositions", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.PersonnelAddresses", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.PersonnelIdentifiers", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.PersonnelPositions", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.Codes", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.ThesaurusEntries", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.Addresses", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.ChemotherapySchemas", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.Medications", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.ChemotherapySchemaInstanceVersions", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.ChemotherapySchemaInstances", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.MedicationReplacements", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.MedicationInstances", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.SmartOncologyPatients", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.EpisodeOfCares", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.CodeAssociations", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.CodeSets", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.Comments", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.PatientContacts", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.Patients", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.PatientAddresses", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.PatientIdentifiers", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.PatientTelecoms", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.PatientContactAddresses", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.PatientContactTelecoms", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.Encounters", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.GlobalThesaurusRoles", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.GlobalThesaurusUserRoles", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.GlobalThesaurusUsers", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.InboundAliases", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.OutboundAliases", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.OutsideUsers", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.PositionPermissions", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.ThesaurusMerges", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.EncounterIdentifiers", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.ErrorMessageLogs", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.HL7MessageLog", "EntityStateCD", "dbo.Codes", "CodeId");
            AddForeignKey("dbo.ProcedeedMessageLogs", "EntityStateCD", "dbo.Codes", "CodeId");

            string setIsDeletedToNullable = $@"ALTER TABLE [ThesaurusEntries] ALTER COLUMN [IsDeleted] bit NULL;";
            string setIsDeletedToNullableCodes = $@"ALTER TABLE [Codes] ALTER COLUMN [IsDeleted] bit NULL;";
            string setIsDeletedToNullableCodeSets = $@"ALTER TABLE [CodeSets] ALTER COLUMN [IsDeleted] bit NULL;";
            SReportsContext sReportsContext = new SReportsContext();
            sReportsContext.Database.ExecuteSqlCommand(setIsDeletedToNullable);
            sReportsContext.Database.ExecuteSqlCommand(setIsDeletedToNullableCodes);
            sReportsContext.Database.ExecuteSqlCommand(setIsDeletedToNullableCodeSets);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.ProcedeedMessageLogs", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.HL7MessageLog", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.ErrorMessageLogs", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.EncounterIdentifiers", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.ThesaurusMerges", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.PositionPermissions", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.OutsideUsers", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.OutboundAliases", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.InboundAliases", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.GlobalThesaurusUsers", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.GlobalThesaurusUserRoles", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.GlobalThesaurusRoles", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.Encounters", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.PatientContactTelecoms", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.PatientContactAddresses", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.PatientTelecoms", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.PatientIdentifiers", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.PatientAddresses", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.Patients", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.PatientContacts", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.Comments", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.CodeSets", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.CodeAssociations", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.EpisodeOfCares", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.SmartOncologyPatients", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.MedicationInstances", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.MedicationReplacements", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.ChemotherapySchemaInstances", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.ChemotherapySchemaInstanceVersions", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.Medications", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.ChemotherapySchemas", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.Addresses", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.ThesaurusEntries", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.Codes", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.PersonnelPositions", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.PersonnelIdentifiers", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.PersonnelAddresses", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.PersonnelAcademicPositions", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.Telecoms", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.PersonnelTeamRelations", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.PersonnelTeams", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.PersonnelTeamOrganizationRelations", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.OrganizationRelations", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.OrganizationIdentifiers", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.Organizations", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.OrganizationClinicalDomains", "EntityStateCD", "dbo.Codes");
            DropForeignKey("dbo.Personnel", "EntityStateCD", "dbo.Codes");
            DropIndex("dbo.EncounterIdentifiers", new[] { "EntityStateCD" });
            DropIndex("dbo.ErrorMessageLogs", new[] { "EntityStateCD" });
            DropIndex("dbo.HL7MessageLog", new[] { "EntityStateCD" });
            DropIndex("dbo.ProcedeedMessageLogs", new[] { "EntityStateCD" });
            DropIndex("dbo.ThesaurusMerges", new[] { "EntityStateCD" });
            DropIndex("dbo.PositionPermissions", new[] { "EntityStateCD" });
            DropIndex("dbo.OutsideUsers", new[] { "EntityStateCD" });
            DropIndex("dbo.OutboundAliases", new[] { "EntityStateCD" });
            DropIndex("dbo.InboundAliases", new[] { "EntityStateCD" });
            DropIndex("dbo.GlobalThesaurusUsers", new[] { "EntityStateCD" });
            DropIndex("dbo.GlobalThesaurusUserRoles", new[] { "EntityStateCD" });
            DropIndex("dbo.GlobalThesaurusRoles", new[] { "EntityStateCD" });
            DropIndex("dbo.Encounters", new[] { "EntityStateCD" });
            DropIndex("dbo.PatientContactTelecoms", new[] { "EntityStateCD" });
            DropIndex("dbo.PatientContactAddresses", new[] { "EntityStateCD" });
            DropIndex("dbo.PatientTelecoms", new[] { "EntityStateCD" });
            DropIndex("dbo.PatientIdentifiers", new[] { "EntityStateCD" });
            DropIndex("dbo.PatientAddresses", new[] { "EntityStateCD" });
            DropIndex("dbo.Patients", new[] { "EntityStateCD" });
            DropIndex("dbo.PatientContacts", new[] { "EntityStateCD" });
            DropIndex("dbo.Comments", new[] { "EntityStateCD" });
            DropIndex("dbo.CodeSets", new[] { "EntityStateCD" });
            DropIndex("dbo.CodeAssociations", new[] { "EntityStateCD" });
            DropIndex("dbo.EpisodeOfCares", new[] { "EntityStateCD" });
            DropIndex("dbo.SmartOncologyPatients", new[] { "EntityStateCD" });
            DropIndex("dbo.MedicationInstances", new[] { "EntityStateCD" });
            DropIndex("dbo.MedicationReplacements", new[] { "EntityStateCD" });
            DropIndex("dbo.ChemotherapySchemaInstanceVersions", new[] { "EntityStateCD" });
            DropIndex("dbo.Medications", new[] { "EntityStateCD" });
            DropIndex("dbo.ChemotherapySchemas", new[] { "EntityStateCD" });
            DropIndex("dbo.ChemotherapySchemaInstances", new[] { "EntityStateCD" });
            DropIndex("dbo.ThesaurusEntries", new[] { "EntityStateCD" });
            DropIndex("dbo.PersonnelPositions", new[] { "EntityStateCD" });
            DropIndex("dbo.PersonnelIdentifiers", new[] { "EntityStateCD" });
            DropIndex("dbo.PersonnelAddresses", new[] { "EntityStateCD" });
            DropIndex("dbo.PersonnelAcademicPositions", new[] { "EntityStateCD" });
            DropIndex("dbo.Telecoms", new[] { "EntityStateCD" });
            DropIndex("dbo.PersonnelTeamRelations", new[] { "EntityStateCD" });
            DropIndex("dbo.PersonnelTeams", new[] { "EntityStateCD" });
            DropIndex("dbo.PersonnelTeamOrganizationRelations", new[] { "EntityStateCD" });
            DropIndex("dbo.OrganizationRelations", new[] { "EntityStateCD" });
            DropIndex("dbo.OrganizationIdentifiers", new[] { "EntityStateCD" });
            DropIndex("dbo.OrganizationClinicalDomains", new[] { "EntityStateCD" });
            DropIndex("dbo.Organizations", new[] { "EntityStateCD" });
            DropIndex("dbo.Personnel", new[] { "EntityStateCD" });
            DropIndex("dbo.Codes", new[] { "EntityStateCD" });
            DropIndex("dbo.Addresses", new[] { "EntityStateCD" });
            DropColumn("dbo.ProcedeedMessageLogs", "EntityStateCD");
            DropColumn("dbo.HL7MessageLog", "EntityStateCD");
            DropColumn("dbo.ErrorMessageLogs", "EntityStateCD");
            DropColumn("dbo.EncounterIdentifiers", "EntityStateCD");
            DropColumn("dbo.ThesaurusMerges", "EntityStateCD");
            DropColumn("dbo.PositionPermissions", "EntityStateCD");
            DropColumn("dbo.OutsideUsers", "EntityStateCD");
            DropColumn("dbo.OutboundAliases", "EntityStateCD");
            DropColumn("dbo.InboundAliases", "EntityStateCD");
            DropColumn("dbo.GlobalThesaurusUsers", "EntityStateCD");
            DropColumn("dbo.GlobalThesaurusUserRoles", "EntityStateCD");
            DropColumn("dbo.GlobalThesaurusRoles", "EntityStateCD");
            DropColumn("dbo.Encounters", "EntityStateCD");
            DropColumn("dbo.PatientContactTelecoms", "EntityStateCD");
            DropColumn("dbo.PatientContactAddresses", "EntityStateCD");
            DropColumn("dbo.PatientTelecoms", "EntityStateCD");
            DropColumn("dbo.PatientIdentifiers", "EntityStateCD");
            DropColumn("dbo.PatientAddresses", "EntityStateCD");
            DropColumn("dbo.Patients", "EntityStateCD");
            DropColumn("dbo.PatientContacts", "EntityStateCD");
            DropColumn("dbo.Comments", "EntityStateCD");
            DropColumn("dbo.CodeSets", "EntityStateCD");
            DropColumn("dbo.CodeAssociations", "EntityStateCD");
            DropColumn("dbo.EpisodeOfCares", "EntityStateCD");
            DropColumn("dbo.SmartOncologyPatients", "EntityStateCD");
            DropColumn("dbo.MedicationInstances", "EntityStateCD");
            DropColumn("dbo.MedicationReplacements", "EntityStateCD");
            DropColumn("dbo.ChemotherapySchemaInstanceVersions", "EntityStateCD");
            DropColumn("dbo.Medications", "EntityStateCD");
            DropColumn("dbo.ChemotherapySchemas", "EntityStateCD");
            DropColumn("dbo.ChemotherapySchemaInstances", "EntityStateCD");
            DropColumn("dbo.ThesaurusEntries", "EntityStateCD");
            DropColumn("dbo.PersonnelPositions", "EntityStateCD");
            DropColumn("dbo.PersonnelIdentifiers", "EntityStateCD");
            DropColumn("dbo.PersonnelAddresses", "EntityStateCD");
            DropColumn("dbo.PersonnelAcademicPositions", "EntityStateCD");
            DropColumn("dbo.Telecoms", "EntityStateCD");
            DropColumn("dbo.PersonnelTeamRelations", "EntityStateCD");
            DropColumn("dbo.PersonnelTeams", "EntityStateCD");
            DropColumn("dbo.PersonnelTeamOrganizationRelations", "EntityStateCD");
            DropColumn("dbo.OrganizationRelations", "EntityStateCD");
            DropColumn("dbo.OrganizationIdentifiers", "EntityStateCD");
            DropColumn("dbo.OrganizationClinicalDomains", "EntityStateCD");
            DropColumn("dbo.Organizations", "EntityStateCD");
            DropColumn("dbo.Personnel", "EntityStateCD");
            DropColumn("dbo.Codes", "EntityStateCD");
            DropColumn("dbo.Addresses", "EntityStateCD");
        }
    }
}
