namespace sReportsV2.Domain.Sql.Migrations
{
    using sReportsV2.Common.Constants;
    using System;
    using System.Configuration;
    using System.Data.Entity.Migrations;
    
    public partial class UpdateDateTimeToDateTimeOffset : DbMigration
    {
        public override void Up()
        {
            string timezone = TimeZoneConstants.CEST;

            DropIndex("dbo.ChemotherapySchemaInstances", "IX_LastUpdate");
            AlterColumn("dbo.ChemotherapySchemaInstances", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ChemotherapySchemaInstances SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ChemotherapySchemaInstances", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.ChemotherapySchemaInstances SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ChemotherapySchemaInstances", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ChemotherapySchemaInstances SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ChemotherapySchemaInstances", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ChemotherapySchemaInstances SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.ChemotherapySchemaInstances", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.ChemotherapySchemas", "IX_LastUpdate");
            AlterColumn("dbo.ChemotherapySchemas", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ChemotherapySchemas SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ChemotherapySchemas", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.ChemotherapySchemas SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ChemotherapySchemas", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ChemotherapySchemas SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ChemotherapySchemas", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ChemotherapySchemas SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.ChemotherapySchemas", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.Personnel", "IX_LastUpdate");
            AlterColumn("dbo.Personnel", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Personnel SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Personnel", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.Personnel SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Personnel", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Personnel SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Personnel", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Personnel SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.Personnel", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.Codes", "IX_LastUpdate");
            AlterColumn("dbo.Codes", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Codes SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Codes", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.Codes SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Codes", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Codes SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Codes", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Codes SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.Codes", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.ThesaurusEntries", "IX_LastUpdate");
            AlterColumn("dbo.ThesaurusEntries", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ThesaurusEntries SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ThesaurusEntries", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.ThesaurusEntries SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ThesaurusEntries", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ThesaurusEntries SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ThesaurusEntries", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ThesaurusEntries SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.ThesaurusEntries", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.Organizations", "IX_LastUpdate");
            AlterColumn("dbo.Organizations", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Organizations SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Organizations", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.Organizations SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Organizations", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Organizations SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Organizations", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Organizations SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.Organizations", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.OrganizationClinicalDomains", "IX_LastUpdate");
            AlterColumn("dbo.OrganizationClinicalDomains", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationClinicalDomains SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationClinicalDomains", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.OrganizationClinicalDomains SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationClinicalDomains", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationClinicalDomains SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationClinicalDomains", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationClinicalDomains SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.OrganizationClinicalDomains", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.OrganizationAddresses", "IX_LastUpdate");
            AlterColumn("dbo.OrganizationAddresses", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationAddresses SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationAddresses", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.OrganizationAddresses SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationAddresses", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationAddresses SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationAddresses", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationAddresses SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.OrganizationAddresses", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.OrganizationCommunicationEntities", "IX_LastUpdate");
            AlterColumn("dbo.OrganizationCommunicationEntities", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationCommunicationEntities SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationCommunicationEntities", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.OrganizationCommunicationEntities SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationCommunicationEntities", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationCommunicationEntities SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationCommunicationEntities", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationCommunicationEntities SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.OrganizationCommunicationEntities", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.OrganizationIdentifiers", "IX_LastUpdate");
            AlterColumn("dbo.OrganizationIdentifiers", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationIdentifiers SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationIdentifiers", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.OrganizationIdentifiers SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationIdentifiers", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationIdentifiers SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationIdentifiers", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationIdentifiers SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.OrganizationIdentifiers", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.OrganizationRelations", "IX_LastUpdate");
            AlterColumn("dbo.OrganizationRelations", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationRelations SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationRelations", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.OrganizationRelations SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationRelations", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationRelations SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationRelations", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationRelations SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.OrganizationRelations", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.PersonnelTeamOrganizationRelations", "IX_LastUpdate");
            AlterColumn("dbo.PersonnelTeamOrganizationRelations", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelTeamOrganizationRelations SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelTeamOrganizationRelations", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.PersonnelTeamOrganizationRelations SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelTeamOrganizationRelations", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelTeamOrganizationRelations SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelTeamOrganizationRelations", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelTeamOrganizationRelations SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.PersonnelTeamOrganizationRelations", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.PersonnelTeams", "IX_LastUpdate");
            AlterColumn("dbo.PersonnelTeams", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelTeams SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelTeams", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.PersonnelTeams SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelTeams", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelTeams SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelTeams", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelTeams SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.PersonnelTeams", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.PersonnelTeamRelations", "IX_LastUpdate");
            AlterColumn("dbo.PersonnelTeamRelations", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelTeamRelations SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelTeamRelations", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.PersonnelTeamRelations SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelTeamRelations", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelTeamRelations SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelTeamRelations", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelTeamRelations SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.PersonnelTeamRelations", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.OrganizationTelecoms", "IX_LastUpdate");
            AlterColumn("dbo.OrganizationTelecoms", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationTelecoms SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationTelecoms", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.OrganizationTelecoms SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationTelecoms", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationTelecoms SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OrganizationTelecoms", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OrganizationTelecoms SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.OrganizationTelecoms", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.PersonnelAcademicPositions", "IX_LastUpdate");
            AlterColumn("dbo.PersonnelAcademicPositions", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelAcademicPositions SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelAcademicPositions", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.PersonnelAcademicPositions SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelAcademicPositions", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelAcademicPositions SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelAcademicPositions", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelAcademicPositions SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.PersonnelAcademicPositions", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.PersonnelAddresses", "IX_LastUpdate");
            AlterColumn("dbo.PersonnelAddresses", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelAddresses SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelAddresses", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.PersonnelAddresses SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelAddresses", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelAddresses SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelAddresses", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelAddresses SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.PersonnelAddresses", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.PersonnelIdentifiers", "IX_LastUpdate");
            AlterColumn("dbo.PersonnelIdentifiers", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelIdentifiers SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelIdentifiers", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.PersonnelIdentifiers SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelIdentifiers", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelIdentifiers SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelIdentifiers", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelIdentifiers SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.PersonnelIdentifiers", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.PersonnelOccupations", "IX_LastUpdate");
            AlterColumn("dbo.PersonnelOccupations", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelOccupations SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelOccupations", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.PersonnelOccupations SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelOccupations", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelOccupations SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelOccupations", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelOccupations SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.PersonnelOccupations", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.PersonnelPositions", "IX_LastUpdate");
            AlterColumn("dbo.PersonnelPositions", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelPositions SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelPositions", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.PersonnelPositions SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelPositions", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelPositions SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelPositions", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelPositions SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.PersonnelPositions", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.Medications", "IX_LastUpdate");
            AlterColumn("dbo.Medications", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Medications SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Medications", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.Medications SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Medications", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Medications SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Medications", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Medications SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.Medications", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.ChemotherapySchemaInstanceVersions", "IX_LastUpdate");
            AlterColumn("dbo.ChemotherapySchemaInstanceVersions", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ChemotherapySchemaInstanceVersions SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ChemotherapySchemaInstanceVersions", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.ChemotherapySchemaInstanceVersions SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ChemotherapySchemaInstanceVersions", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ChemotherapySchemaInstanceVersions SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ChemotherapySchemaInstanceVersions", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ChemotherapySchemaInstanceVersions SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.ChemotherapySchemaInstanceVersions", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.MedicationReplacements", "IX_LastUpdate");
            AlterColumn("dbo.MedicationReplacements", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.MedicationReplacements SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.MedicationReplacements", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.MedicationReplacements SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.MedicationReplacements", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.MedicationReplacements SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.MedicationReplacements", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.MedicationReplacements SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.MedicationReplacements", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.MedicationInstances", "IX_LastUpdate");
            AlterColumn("dbo.MedicationInstances", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.MedicationInstances SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.MedicationInstances", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.MedicationInstances SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.MedicationInstances", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.MedicationInstances SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.MedicationInstances", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.MedicationInstances SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.MedicationInstances", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.SmartOncologyPatients", "IX_LastUpdate");
            AlterColumn("dbo.SmartOncologyPatients", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.SmartOncologyPatients SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.SmartOncologyPatients", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.SmartOncologyPatients SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.SmartOncologyPatients", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.SmartOncologyPatients SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.SmartOncologyPatients", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.SmartOncologyPatients SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.SmartOncologyPatients", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.EpisodeOfCares", "IX_LastUpdate");
            AlterColumn("dbo.EpisodeOfCares", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.EpisodeOfCares SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.EpisodeOfCares", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.EpisodeOfCares SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.EpisodeOfCares", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.EpisodeOfCares SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.EpisodeOfCares", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.EpisodeOfCares SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.EpisodeOfCares", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.Encounters", "IX_LastUpdate");
            AlterColumn("dbo.Encounters", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Encounters SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Encounters", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.Encounters SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Encounters", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Encounters SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Encounters", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Encounters SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.Encounters", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.EncounterIdentifiers", "IX_LastUpdate");
            AlterColumn("dbo.EncounterIdentifiers", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.EncounterIdentifiers SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.EncounterIdentifiers", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.EncounterIdentifiers SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.EncounterIdentifiers", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.EncounterIdentifiers SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.EncounterIdentifiers", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.EncounterIdentifiers SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.EncounterIdentifiers", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.Patients", "IX_LastUpdate");
            AlterColumn("dbo.Patients", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Patients SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Patients", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.Patients SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Patients", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Patients SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Patients", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Patients SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.Patients", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.PatientAddresses", "IX_LastUpdate");
            AlterColumn("dbo.PatientAddresses", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientAddresses SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientAddresses", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.PatientAddresses SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientAddresses", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientAddresses SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientAddresses", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientAddresses SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.PatientAddresses", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.PatientContacts", "IX_LastUpdate");
            AlterColumn("dbo.PatientContacts", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientContacts SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientContacts", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.PatientContacts SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientContacts", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientContacts SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientContacts", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientContacts SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.PatientContacts", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.PatientContactAddresses", "IX_LastUpdate");
            AlterColumn("dbo.PatientContactAddresses", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientContactAddresses SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientContactAddresses", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.PatientContactAddresses SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientContactAddresses", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientContactAddresses SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientContactAddresses", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientContactAddresses SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.PatientContactAddresses", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.PatientContactTelecoms", "IX_LastUpdate");
            AlterColumn("dbo.PatientContactTelecoms", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientContactTelecoms SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientContactTelecoms", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.PatientContactTelecoms SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientContactTelecoms", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientContactTelecoms SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientContactTelecoms", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientContactTelecoms SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.PatientContactTelecoms", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.PatientIdentifiers", "IX_LastUpdate");
            AlterColumn("dbo.PatientIdentifiers", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientIdentifiers SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientIdentifiers", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.PatientIdentifiers SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientIdentifiers", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientIdentifiers SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientIdentifiers", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientIdentifiers SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.PatientIdentifiers", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.PatientTelecoms", "IX_LastUpdate");
            AlterColumn("dbo.PatientTelecoms", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientTelecoms SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientTelecoms", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.PatientTelecoms SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientTelecoms", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientTelecoms SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PatientTelecoms", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PatientTelecoms SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.PatientTelecoms", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.ProjectPatientRelations", "IX_LastUpdate");
            AlterColumn("dbo.ProjectPatientRelations", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ProjectPatientRelations SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ProjectPatientRelations", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.ProjectPatientRelations SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ProjectPatientRelations", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ProjectPatientRelations SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ProjectPatientRelations", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ProjectPatientRelations SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.ProjectPatientRelations", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.Projects", "IX_LastUpdate");
            AlterColumn("dbo.Projects", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Projects SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Projects", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.Projects SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Projects", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Projects SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Projects", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Projects SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.Projects", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.ProjectDocumentRelations", "IX_LastUpdate");
            AlterColumn("dbo.ProjectDocumentRelations", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ProjectDocumentRelations SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ProjectDocumentRelations", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.ProjectDocumentRelations SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ProjectDocumentRelations", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ProjectDocumentRelations SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ProjectDocumentRelations", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ProjectDocumentRelations SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.ProjectDocumentRelations", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.ProjectPersonnelRelations", "IX_LastUpdate");
            AlterColumn("dbo.ProjectPersonnelRelations", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ProjectPersonnelRelations SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ProjectPersonnelRelations", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.ProjectPersonnelRelations SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ProjectPersonnelRelations", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ProjectPersonnelRelations SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ProjectPersonnelRelations", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ProjectPersonnelRelations SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.ProjectPersonnelRelations", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.PersonnelEncounterRelations", "IX_LastUpdate");
            AlterColumn("dbo.PersonnelEncounterRelations", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelEncounterRelations SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelEncounterRelations", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.PersonnelEncounterRelations SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelEncounterRelations", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelEncounterRelations SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PersonnelEncounterRelations", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PersonnelEncounterRelations SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.PersonnelEncounterRelations", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.Tasks", "IX_LastUpdate");
            AlterColumn("dbo.Tasks", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Tasks SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Tasks", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.Tasks SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Tasks", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Tasks SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Tasks", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Tasks SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.Tasks", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.TaskDocuments", "IX_LastUpdate");
            AlterColumn("dbo.TaskDocuments", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.TaskDocuments SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.TaskDocuments", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.TaskDocuments SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.TaskDocuments", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.TaskDocuments SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.TaskDocuments", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.TaskDocuments SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.TaskDocuments", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.ClinicalTrials", "IX_LastUpdate");
            AlterColumn("dbo.ClinicalTrials", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ClinicalTrials SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ClinicalTrials", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.ClinicalTrials SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ClinicalTrials", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ClinicalTrials SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ClinicalTrials", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ClinicalTrials SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.ClinicalTrials", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.CodeAssociations", "IX_LastUpdate");
            AlterColumn("dbo.CodeAssociations", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.CodeAssociations SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.CodeAssociations", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.CodeAssociations SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.CodeAssociations", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.CodeAssociations SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.CodeAssociations", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.CodeAssociations SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.CodeAssociations", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.CodeSets", "IX_LastUpdate");
            AlterColumn("dbo.CodeSets", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.CodeSets SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.CodeSets", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.CodeSets SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.CodeSets", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.CodeSets SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.CodeSets", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.CodeSets SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.CodeSets", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.Comments", "IX_LastUpdate");
            AlterColumn("dbo.Comments", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Comments SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Comments", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.Comments SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Comments", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Comments SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Comments", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Comments SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.Comments", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.ErrorMessageLogs", "IX_LastUpdate");
            AlterColumn("dbo.ErrorMessageLogs", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ErrorMessageLogs SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ErrorMessageLogs", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.ErrorMessageLogs SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ErrorMessageLogs", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ErrorMessageLogs SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ErrorMessageLogs", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ErrorMessageLogs SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.ErrorMessageLogs", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.HL7MessageLogs", "IX_LastUpdate");
            AlterColumn("dbo.HL7MessageLogs", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.HL7MessageLogs SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.HL7MessageLogs", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.HL7MessageLogs SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.HL7MessageLogs", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.HL7MessageLogs SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.HL7MessageLogs", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.HL7MessageLogs SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.HL7MessageLogs", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.GlobalThesaurusRoles", "IX_LastUpdate");
            AlterColumn("dbo.GlobalThesaurusRoles", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.GlobalThesaurusRoles SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.GlobalThesaurusRoles", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.GlobalThesaurusRoles SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.GlobalThesaurusRoles", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.GlobalThesaurusRoles SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.GlobalThesaurusRoles", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.GlobalThesaurusRoles SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.GlobalThesaurusRoles", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.GlobalThesaurusUserRoles", "IX_LastUpdate");
            AlterColumn("dbo.GlobalThesaurusUserRoles", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.GlobalThesaurusUserRoles SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.GlobalThesaurusUserRoles", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.GlobalThesaurusUserRoles SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.GlobalThesaurusUserRoles", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.GlobalThesaurusUserRoles SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.GlobalThesaurusUserRoles", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.GlobalThesaurusUserRoles SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.GlobalThesaurusUserRoles", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.GlobalThesaurusUsers", "IX_LastUpdate");
            AlterColumn("dbo.GlobalThesaurusUsers", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.GlobalThesaurusUsers SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.GlobalThesaurusUsers", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.GlobalThesaurusUsers SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.GlobalThesaurusUsers", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.GlobalThesaurusUsers SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.GlobalThesaurusUsers", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.GlobalThesaurusUsers SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.GlobalThesaurusUsers", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.InboundAliases", "IX_LastUpdate");
            AlterColumn("dbo.InboundAliases", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.InboundAliases SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.InboundAliases", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.InboundAliases SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.InboundAliases", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.InboundAliases SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.InboundAliases", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.InboundAliases SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.InboundAliases", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.OutboundAliases", "IX_LastUpdate");
            AlterColumn("dbo.OutboundAliases", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OutboundAliases SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OutboundAliases", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.OutboundAliases SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OutboundAliases", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OutboundAliases SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OutboundAliases", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OutboundAliases SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.OutboundAliases", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.OutsideUsers", "IX_LastUpdate");
            AlterColumn("dbo.OutsideUsers", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OutsideUsers SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OutsideUsers", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.OutsideUsers SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OutsideUsers", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OutsideUsers SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OutsideUsers", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OutsideUsers SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.OutsideUsers", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.OutsideUserAddresses", "IX_LastUpdate");
            AlterColumn("dbo.OutsideUserAddresses", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OutsideUserAddresses SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OutsideUserAddresses", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.OutsideUserAddresses SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OutsideUserAddresses", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OutsideUserAddresses SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.OutsideUserAddresses", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.OutsideUserAddresses SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.OutsideUserAddresses", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.PositionPermissions", "IX_LastUpdate");
            AlterColumn("dbo.PositionPermissions", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PositionPermissions SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PositionPermissions", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.PositionPermissions SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PositionPermissions", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PositionPermissions SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.PositionPermissions", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.PositionPermissions SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.PositionPermissions", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.ThesaurusMerges", "IX_LastUpdate");
            AlterColumn("dbo.ThesaurusMerges", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ThesaurusMerges SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ThesaurusMerges", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.ThesaurusMerges SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ThesaurusMerges", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ThesaurusMerges SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.ThesaurusMerges", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.ThesaurusMerges SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.ThesaurusMerges", "LastUpdate", unique: false, name: "IX_LastUpdate");

            DropIndex("dbo.Transactions", "IX_LastUpdate");
            AlterColumn("dbo.Transactions", "EntryDatetime", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Transactions SET EntryDatetime = (SELECT EntryDatetime AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Transactions", "LastUpdate", c => c.DateTimeOffset(precision: 7));
            Sql($"UPDATE dbo.Transactions SET LastUpdate = (SELECT LastUpdate AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Transactions", "ActiveFrom", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Transactions SET ActiveFrom = (SELECT ActiveFrom AT TIME ZONE '{timezone}')");
            AlterColumn("dbo.Transactions", "ActiveTo", c => c.DateTimeOffset(nullable: false, precision: 7));
            Sql($"UPDATE dbo.Transactions SET ActiveTo = (SELECT ActiveTo AT TIME ZONE '{timezone}')");
            CreateIndex("dbo.Transactions", "LastUpdate", unique: false, name: "IX_LastUpdate");
        }

        public override void Down()
        {
            AlterColumn("dbo.Transactions", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Transactions", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Transactions", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.Transactions", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ThesaurusMerges", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ThesaurusMerges", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ThesaurusMerges", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.ThesaurusMerges", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PositionPermissions", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PositionPermissions", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PositionPermissions", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.PositionPermissions", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OutsideUserAddresses", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OutsideUserAddresses", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OutsideUserAddresses", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.OutsideUserAddresses", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OutsideUsers", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OutsideUsers", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OutsideUsers", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.OutsideUsers", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OutboundAliases", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OutboundAliases", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OutboundAliases", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.OutboundAliases", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.InboundAliases", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.InboundAliases", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.InboundAliases", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.InboundAliases", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GlobalThesaurusUsers", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GlobalThesaurusUsers", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GlobalThesaurusUsers", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.GlobalThesaurusUsers", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GlobalThesaurusUserRoles", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GlobalThesaurusUserRoles", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GlobalThesaurusUserRoles", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.GlobalThesaurusUserRoles", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GlobalThesaurusRoles", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GlobalThesaurusRoles", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GlobalThesaurusRoles", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.GlobalThesaurusRoles", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.HL7MessageLogs", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.HL7MessageLogs", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.HL7MessageLogs", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.HL7MessageLogs", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ErrorMessageLogs", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ErrorMessageLogs", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ErrorMessageLogs", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.ErrorMessageLogs", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Comments", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Comments", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Comments", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.Comments", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.CodeSets", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.CodeSets", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.CodeSets", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.CodeSets", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.CodeAssociations", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.CodeAssociations", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.CodeAssociations", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.CodeAssociations", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ClinicalTrials", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ClinicalTrials", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ClinicalTrials", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.ClinicalTrials", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.TaskDocuments", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.TaskDocuments", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.TaskDocuments", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.TaskDocuments", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Tasks", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Tasks", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Tasks", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.Tasks", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelEncounterRelations", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelEncounterRelations", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelEncounterRelations", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.PersonnelEncounterRelations", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ProjectPersonnelRelations", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ProjectPersonnelRelations", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ProjectPersonnelRelations", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.ProjectPersonnelRelations", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ProjectDocumentRelations", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ProjectDocumentRelations", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ProjectDocumentRelations", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.ProjectDocumentRelations", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Projects", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Projects", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Projects", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.Projects", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ProjectPatientRelations", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ProjectPatientRelations", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ProjectPatientRelations", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.ProjectPatientRelations", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientTelecoms", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientTelecoms", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientTelecoms", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.PatientTelecoms", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientIdentifiers", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientIdentifiers", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientIdentifiers", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.PatientIdentifiers", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientContactTelecoms", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientContactTelecoms", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientContactTelecoms", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.PatientContactTelecoms", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientContactAddresses", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientContactAddresses", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientContactAddresses", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.PatientContactAddresses", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientContacts", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientContacts", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientContacts", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.PatientContacts", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientAddresses", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientAddresses", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PatientAddresses", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.PatientAddresses", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Patients", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Patients", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Patients", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.Patients", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.EncounterIdentifiers", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.EncounterIdentifiers", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.EncounterIdentifiers", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.EncounterIdentifiers", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Encounters", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Encounters", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Encounters", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.Encounters", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.EpisodeOfCares", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.EpisodeOfCares", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.EpisodeOfCares", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.EpisodeOfCares", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.SmartOncologyPatients", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.SmartOncologyPatients", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.SmartOncologyPatients", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.SmartOncologyPatients", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.MedicationInstances", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.MedicationInstances", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.MedicationInstances", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.MedicationInstances", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.MedicationReplacements", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.MedicationReplacements", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.MedicationReplacements", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.MedicationReplacements", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ChemotherapySchemaInstanceVersions", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ChemotherapySchemaInstanceVersions", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ChemotherapySchemaInstanceVersions", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.ChemotherapySchemaInstanceVersions", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Medications", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Medications", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Medications", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.Medications", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelPositions", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelPositions", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelPositions", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.PersonnelPositions", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelOccupations", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelOccupations", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelOccupations", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.PersonnelOccupations", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelIdentifiers", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelIdentifiers", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelIdentifiers", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.PersonnelIdentifiers", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelAddresses", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelAddresses", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelAddresses", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.PersonnelAddresses", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelAcademicPositions", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelAcademicPositions", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelAcademicPositions", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.PersonnelAcademicPositions", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationTelecoms", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationTelecoms", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationTelecoms", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.OrganizationTelecoms", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelTeamRelations", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelTeamRelations", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelTeamRelations", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.PersonnelTeamRelations", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelTeams", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelTeams", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelTeams", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.PersonnelTeams", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelTeamOrganizationRelations", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelTeamOrganizationRelations", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PersonnelTeamOrganizationRelations", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.PersonnelTeamOrganizationRelations", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationRelations", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationRelations", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationRelations", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.OrganizationRelations", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationIdentifiers", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationIdentifiers", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationIdentifiers", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.OrganizationIdentifiers", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationCommunicationEntities", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationCommunicationEntities", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationCommunicationEntities", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.OrganizationCommunicationEntities", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationAddresses", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationAddresses", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationAddresses", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.OrganizationAddresses", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationClinicalDomains", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationClinicalDomains", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.OrganizationClinicalDomains", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.OrganizationClinicalDomains", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Organizations", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Organizations", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Organizations", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.Organizations", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ThesaurusEntries", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ThesaurusEntries", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ThesaurusEntries", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.ThesaurusEntries", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Codes", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Codes", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Codes", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.Codes", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Personnel", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Personnel", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Personnel", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.Personnel", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ChemotherapySchemas", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ChemotherapySchemas", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ChemotherapySchemas", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.ChemotherapySchemas", "EntryDatetime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ChemotherapySchemaInstances", "ActiveTo", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ChemotherapySchemaInstances", "ActiveFrom", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ChemotherapySchemaInstances", "LastUpdate", c => c.DateTime());
            AlterColumn("dbo.ChemotherapySchemaInstances", "EntryDatetime", c => c.DateTime(nullable: false));
        }
    }
}
