namespace sReportsV2.Domain.Sql.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ExtendBaseEntityActiveFromTo : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Addresses", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.Addresses", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.Codes", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.Codes", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.Personnel", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.Personnel", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.Organizations", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.Organizations", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.OrganizationClinicalDomains", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.OrganizationClinicalDomains", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.OrganizationIdentifiers", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.OrganizationIdentifiers", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.OrganizationRelations", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.OrganizationRelations", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.PersonnelTeamOrganizationRelations", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.PersonnelTeamOrganizationRelations", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.PersonnelTeams", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.PersonnelTeams", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.PersonnelTeamRelations", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.PersonnelTeamRelations", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.Telecoms", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.Telecoms", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.PersonnelAcademicPositions", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.PersonnelAcademicPositions", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.PersonnelAddresses", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.PersonnelAddresses", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.PersonnelIdentifiers", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.PersonnelIdentifiers", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.PersonnelPositions", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.PersonnelPositions", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.ThesaurusEntries", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.ThesaurusEntries", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.ChemotherapySchemaInstances", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.ChemotherapySchemaInstances", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.ChemotherapySchemas", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.ChemotherapySchemas", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.Medications", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.Medications", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.ChemotherapySchemaInstanceVersions", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.ChemotherapySchemaInstanceVersions", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.MedicationReplacements", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.MedicationReplacements", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.MedicationInstances", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.MedicationInstances", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.SmartOncologyPatients", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.SmartOncologyPatients", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.EpisodeOfCares", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.EpisodeOfCares", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.CodeAssociations", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.CodeAssociations", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.CodeSets", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.CodeSets", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.Comments", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.Comments", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.PatientContacts", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.PatientContacts", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.Patients", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.Patients", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.PatientAddresses", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.PatientAddresses", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.PatientIdentifiers", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.PatientIdentifiers", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.PatientTelecoms", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.PatientTelecoms", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.PatientContactAddresses", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.PatientContactAddresses", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.PatientContactTelecoms", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.PatientContactTelecoms", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.Encounters", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.Encounters", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.GlobalThesaurusRoles", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.GlobalThesaurusRoles", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.GlobalThesaurusUserRoles", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.GlobalThesaurusUserRoles", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.GlobalThesaurusUsers", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.GlobalThesaurusUsers", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.InboundAliases", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.InboundAliases", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.OutboundAliases", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.OutboundAliases", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.OutsideUsers", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.OutsideUsers", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.PositionPermissions", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.PositionPermissions", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
            AddColumn("dbo.ThesaurusMerges", "ActiveFrom", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '2022-01-01 12:00:00', 120)"));
            AddColumn("dbo.ThesaurusMerges", "ActiveTo", c => c.DateTime(nullable: false, defaultValueSql: "CONVERT(datetime, '9999-12-31 23:59:59', 120)"));
        }
        
        public override void Down()
        {
            DropColumn("dbo.ThesaurusMerges", "ActiveTo");
            DropColumn("dbo.ThesaurusMerges", "ActiveFrom");
            DropColumn("dbo.PositionPermissions", "ActiveTo");
            DropColumn("dbo.PositionPermissions", "ActiveFrom");
            DropColumn("dbo.OutsideUsers", "ActiveTo");
            DropColumn("dbo.OutsideUsers", "ActiveFrom");
            DropColumn("dbo.OutboundAliases", "ActiveTo");
            DropColumn("dbo.OutboundAliases", "ActiveFrom");
            DropColumn("dbo.InboundAliases", "ActiveTo");
            DropColumn("dbo.InboundAliases", "ActiveFrom");
            DropColumn("dbo.GlobalThesaurusUsers", "ActiveTo");
            DropColumn("dbo.GlobalThesaurusUsers", "ActiveFrom");
            DropColumn("dbo.GlobalThesaurusUserRoles", "ActiveTo");
            DropColumn("dbo.GlobalThesaurusUserRoles", "ActiveFrom");
            DropColumn("dbo.GlobalThesaurusRoles", "ActiveTo");
            DropColumn("dbo.GlobalThesaurusRoles", "ActiveFrom");
            DropColumn("dbo.Encounters", "ActiveTo");
            DropColumn("dbo.Encounters", "ActiveFrom");
            DropColumn("dbo.PatientContactTelecoms", "ActiveTo");
            DropColumn("dbo.PatientContactTelecoms", "ActiveFrom");
            DropColumn("dbo.PatientContactAddresses", "ActiveTo");
            DropColumn("dbo.PatientContactAddresses", "ActiveFrom");
            DropColumn("dbo.PatientTelecoms", "ActiveTo");
            DropColumn("dbo.PatientTelecoms", "ActiveFrom");
            DropColumn("dbo.PatientIdentifiers", "ActiveTo");
            DropColumn("dbo.PatientIdentifiers", "ActiveFrom");
            DropColumn("dbo.PatientAddresses", "ActiveTo");
            DropColumn("dbo.PatientAddresses", "ActiveFrom");
            DropColumn("dbo.Patients", "ActiveTo");
            DropColumn("dbo.Patients", "ActiveFrom");
            DropColumn("dbo.PatientContacts", "ActiveTo");
            DropColumn("dbo.PatientContacts", "ActiveFrom");
            DropColumn("dbo.Comments", "ActiveTo");
            DropColumn("dbo.Comments", "ActiveFrom");
            DropColumn("dbo.CodeSets", "ActiveTo");
            DropColumn("dbo.CodeSets", "ActiveFrom");
            DropColumn("dbo.CodeAssociations", "ActiveTo");
            DropColumn("dbo.CodeAssociations", "ActiveFrom");
            DropColumn("dbo.EpisodeOfCares", "ActiveTo");
            DropColumn("dbo.EpisodeOfCares", "ActiveFrom");
            DropColumn("dbo.SmartOncologyPatients", "ActiveTo");
            DropColumn("dbo.SmartOncologyPatients", "ActiveFrom");
            DropColumn("dbo.MedicationInstances", "ActiveTo");
            DropColumn("dbo.MedicationInstances", "ActiveFrom");
            DropColumn("dbo.MedicationReplacements", "ActiveTo");
            DropColumn("dbo.MedicationReplacements", "ActiveFrom");
            DropColumn("dbo.ChemotherapySchemaInstanceVersions", "ActiveTo");
            DropColumn("dbo.ChemotherapySchemaInstanceVersions", "ActiveFrom");
            DropColumn("dbo.Medications", "ActiveTo");
            DropColumn("dbo.Medications", "ActiveFrom");
            DropColumn("dbo.ChemotherapySchemas", "ActiveTo");
            DropColumn("dbo.ChemotherapySchemas", "ActiveFrom");
            DropColumn("dbo.ChemotherapySchemaInstances", "ActiveTo");
            DropColumn("dbo.ChemotherapySchemaInstances", "ActiveFrom");
            DropColumn("dbo.ThesaurusEntries", "ActiveTo");
            DropColumn("dbo.ThesaurusEntries", "ActiveFrom");
            DropColumn("dbo.PersonnelPositions", "ActiveTo");
            DropColumn("dbo.PersonnelPositions", "ActiveFrom");
            DropColumn("dbo.PersonnelIdentifiers", "ActiveTo");
            DropColumn("dbo.PersonnelIdentifiers", "ActiveFrom");
            DropColumn("dbo.PersonnelAddresses", "ActiveTo");
            DropColumn("dbo.PersonnelAddresses", "ActiveFrom");
            DropColumn("dbo.PersonnelAcademicPositions", "ActiveTo");
            DropColumn("dbo.PersonnelAcademicPositions", "ActiveFrom");
            DropColumn("dbo.Telecoms", "ActiveTo");
            DropColumn("dbo.Telecoms", "ActiveFrom");
            DropColumn("dbo.PersonnelTeamRelations", "ActiveTo");
            DropColumn("dbo.PersonnelTeamRelations", "ActiveFrom");
            DropColumn("dbo.PersonnelTeams", "ActiveTo");
            DropColumn("dbo.PersonnelTeams", "ActiveFrom");
            DropColumn("dbo.PersonnelTeamOrganizationRelations", "ActiveTo");
            DropColumn("dbo.PersonnelTeamOrganizationRelations", "ActiveFrom");
            DropColumn("dbo.OrganizationRelations", "ActiveTo");
            DropColumn("dbo.OrganizationRelations", "ActiveFrom");
            DropColumn("dbo.OrganizationIdentifiers", "ActiveTo");
            DropColumn("dbo.OrganizationIdentifiers", "ActiveFrom");
            DropColumn("dbo.OrganizationClinicalDomains", "ActiveTo");
            DropColumn("dbo.OrganizationClinicalDomains", "ActiveFrom");
            DropColumn("dbo.Organizations", "ActiveTo");
            DropColumn("dbo.Organizations", "ActiveFrom");
            DropColumn("dbo.Personnel", "ActiveTo");
            DropColumn("dbo.Personnel", "ActiveFrom");
            DropColumn("dbo.Codes", "ActiveTo");
            DropColumn("dbo.Codes", "ActiveFrom");
            DropColumn("dbo.Addresses", "ActiveTo");
            DropColumn("dbo.Addresses", "ActiveFrom");
        }
    }
}
